version: '2.3'

services:
  elixir_base:
    build:
      context: elixir
    volumes:
      - ./app/elixir:/app
    working_dir: /app
    command: []

  elixir_init:
    extends:
      file: docker-compose.elixir.yml
      service: elixir_base
    user: "root"
    command: /bin/bash -c "chown 1000:1000 ./"

  elixir:
    extends:
      file: docker-compose.elixir.yml
      service: elixir_base
    command: []
